# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements-dev.txt
            # Download spark 2.2.0
            "[ -f spark ] || mkdir spark && pushd spark && wget https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz && popd && tar -xf ./spark/spark-2.2.0-bin-hadoop2.7.tgz"
            # Start the local master
            pushd spark-2.2.0-bin-hadoop2.7
            ./sbin/start-master.sh -h localhost
            ./sbin/start-slave.sh spark://localhost:7077
            popd
      - save_cache:
          paths:
            venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests .

      - store_artifacts:
          path: test-reports
          destination: test-reports

